language: python
python:
  - 2.7
  - 3.6
install:
  - python setup.py install
script: pytest -s tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
